@endpoint = http://localhost:{{$dotenv PORT}}

### Home page 
GET {{ endpoint }}/


### /login
POST {{endpoint}}/login
Content-Type: application/json

{
    "email" : "test@admin88.com",
    "password" : "test"
}